import NavBar from './components/Navbar'
import './globals.css'
import { outfit } from './ui/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-full'>
      <body className={`${outfit.className} bg-pageBlack p-6 lg:p-8 lg:flex h-full antialiased`}>
        <header>
          <NavBar />
        </header>
        <main className='py-6 lg:p-8 lg:pr-0 lg:pb-0 h-full w-full lg:overflow-auto lg:scrollbar-none'>
          {children}
        </main>
      </body>
    </html>
  )
}
