export const env = {
  TMDB_HOSTNAME: process.env.API_URL,
  TMDB_API_KEY: process.env.TMDB_API_KEY,
  TMDB_IMAGES_URL: process.env.IMAGES_URL,
  TMDB_SEARCH_GLOBAL: process.env.SEARCH_GLOBAL,
  TMDB_ALL_MOVIES: process.env.ALL_MOVIES,
  TMDB_SEARCH_MOVIES: process.env.SEARCH_MOVIE,
  TMDB_ALL_GENRES: process.env.ALL_MOVIES_GENRES,
  TMDB_ALL_TV: process.env.ALL_TV,
  TMDB_ALL_TV_GENRES: process.env.ALL_TV_GENRES,
  TMDB_SEARCH_TV: process.env.SEARCH_TV,
  TMDB_UPCOMING_MOVIES: process.env.UPCOMING_MOVIES,
  TMDB_TOP_RATED_MOVIES: process.env.TOP_RATED_MOVIES,
  TMDB_POPULAR_MOVIES: process.env.POPULAR_MOVIES,
  TMDB_NOW_PLAYING_MOVIES: process.env.NOW_PLAYING_MOVIES,
  TMDB_MOVIE_DETAILS: process.env.MOVIE_DETAILS,

  TMDB_TV_DETAILS: process.env.TV_DETAILS,
  TMDB_TV_AIRING_TODAY: process.env.TV_AIRING_TODAY,
  TMDB_TV_ON_THE_AIR: process.env.TV_ON_THE_AIR,
  TMDB_TV_POPULAR: process.env.TV_POPULAR,
  TMDB_TV_TOP_RATED: process.env.TV_TOP_RATED
}